// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package todomock

import (
	models "github.com/phalpin/GoGoGadgetRESTAPI/todo/models"
	mock "github.com/stretchr/testify/mock"
)

// IToDoRepo is an autogenerated mock type for the IToDoRepo type
type IToDoRepo struct {
	mock.Mock
}

// InsertOne provides a mock function with given fields: _a0
func (_m *IToDoRepo) InsertOne(_a0 *models.ToDo) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ToDo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
